// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAchMU4DAhIZns3C0zb701QT44czKzShGw',
    appId: '1:380805675112:web:6ebcda74ff7d0f7c4ee3dd',
    messagingSenderId: '380805675112',
    projectId: 'app-asher-lynx',
    authDomain: 'app-asher-lynx.firebaseapp.com',
    storageBucket: 'app-asher-lynx.firebasestorage.app',
    measurementId: 'G-RKY6WZ36Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQmQLD5FSMTT_yzVayTqg0tB4T_cO8rFw',
    appId: '1:380805675112:android:fde86e6bf1137b7b4ee3dd',
    messagingSenderId: '380805675112',
    projectId: 'app-asher-lynx',
    storageBucket: 'app-asher-lynx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWPju7JPzZNDF1JsNnThj6P681cQCezsg',
    appId: '1:380805675112:ios:3f824234fb527cb44ee3dd',
    messagingSenderId: '380805675112',
    projectId: 'app-asher-lynx',
    storageBucket: 'app-asher-lynx.firebasestorage.app',
    iosClientId: '380805675112-9fc4vno1s6t7db30udaaj264f7a17f1g.apps.googleusercontent.com',
    iosBundleId: 'app.lynx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWPju7JPzZNDF1JsNnThj6P681cQCezsg',
    appId: '1:380805675112:ios:3f824234fb527cb44ee3dd',
    messagingSenderId: '380805675112',
    projectId: 'app-asher-lynx',
    storageBucket: 'app-asher-lynx.firebasestorage.app',
    iosClientId: '380805675112-9fc4vno1s6t7db30udaaj264f7a17f1g.apps.googleusercontent.com',
    iosBundleId: 'app.lynx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAchMU4DAhIZns3C0zb701QT44czKzShGw',
    appId: '1:380805675112:web:21aedc08e0bcd9504ee3dd',
    messagingSenderId: '380805675112',
    projectId: 'app-asher-lynx',
    authDomain: 'app-asher-lynx.firebaseapp.com',
    storageBucket: 'app-asher-lynx.firebasestorage.app',
    measurementId: 'G-1RVWREEPRE',
  );
}
